import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { getAdminServices, createService, updateService } from '../../services/serviceApi'
import { getAdminCategories } from '../../services/serviceCategoryApi'
import { formatPrice, serviceImageUrl } from '../../utils/serviceDisplay'
import { errorMessage } from '../../utils/errorMessage'
const empty={name:'',category_id:'',description:'',benefits:'',suitability_notes:'',price:'',duration_minutes:'',status:'active'}
export default function ServiceManagementPage() {
  const [rows,setRows]=useState([]),[categories,setCategories]=useState([]),[form,setForm]=useState(empty),[editId,setEditId]=useState(null)
  const [image,setImage]=useState(null),[oldImage,setOldImage]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
  const fileInput=useRef(null)
  async function load(){setLoading(true);try{const [services,list]=await Promise.all([getAdminServices(),getAdminCategories()]);setRows(services.data.data);setCategories(list.data.data)}finally{setLoading(false)}}
  useEffect(()=>{load().catch(failure=>setError(errorMessage(failure)))},[])
  function reset(){setEditId(null);setForm(empty);setImage(null);setOldImage(null);if(fileInput.current)fileInput.current.value=''}
  function change(event){setForm({...form,[event.target.name]:event.target.value})}
  function chooseImage(event){const file=event.target.files[0];setError('');if(file && (!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)){setError('Chọn ảnh JPG, PNG hoặc WebP tối đa 5 MB.');event.target.value='';setImage(null);return}setImage(file||null)}
  async function save(event){event.preventDefault();setError('');setNotice('');if(!form.name.trim()||!form.description.trim())return setError('Vui lòng nhập tên và mô tả.');setBusy(true);try{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,value));if(image)body.append('image',image);if(editId)await updateService(editId,body);else await createService(body);reset();setNotice('Đã lưu dịch vụ.');await load()}catch(failure){setError(errorMessage(failure))}finally{setBusy(false)}}
  async function toggle(row){setBusy(true);setError('');setNotice('');try{const status=row.status==='active'?'inactive':'active';await updateService(row.id,{status});if(editId===row.id)setForm(current=>({...current,status}));await load();setNotice('Đã cập nhật trạng thái.')}catch(failure){setError(errorMessage(failure))}finally{setBusy(false)}}
  function edit(row){setEditId(row.id);setForm(Object.fromEntries(Object.keys(empty).map(key=>[key,String(row[key]??'')])));setImage(null);setOldImage(row.image_url);if(fileInput.current)fileInput.current.value='';setError('');setNotice('');window.scrollTo({top:0,behavior:'smooth'})}
  return <section><h1 className="text-3xl font-semibold">Quản lý dịch vụ</h1><p className="mt-3 text-stone-600">Thêm thông tin, ảnh và quản lý trạng thái cung cấp dịch vụ.</p>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{notice&&<p role="status" className="mt-4 text-emerald-800">{notice}</p>}
  <form onSubmit={save} className="my-6 space-y-4 rounded-2xl border border-stone-200 bg-white p-6"><h2 className="text-xl font-semibold">{editId?'Sửa dịch vụ':'Thêm dịch vụ'}</h2>{!categories.length&&!loading&&<p className="text-amber-800">Bạn cần <Link className="underline" to="/admin/categories">tạo danh mục</Link> trước.</p>}
  <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Tên dịch vụ<input className="form-input" name="name" required maxLength={150} value={form.name} onChange={change}/></label><label className="block text-sm font-medium">Danh mục<select className="form-input" name="category_id" required value={form.category_id} onChange={change}><option value="">Chọn danh mục</option>{categories.map(row=><option key={row.id} value={row.id}>{row.name}{row.status==='inactive'?' (đang tắt)':''}</option>)}</select></label></div>
  <label className="block text-sm font-medium">Mô tả<textarea className="form-input" rows={3} name="description" required value={form.description} onChange={change}/></label>
  <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Lợi ích<textarea className="form-input" rows={3} name="benefits" value={form.benefits} onChange={change}/></label><label className="block text-sm font-medium">Thông tin phù hợp và lưu ý<textarea className="form-input" rows={3} name="suitability_notes" value={form.suitability_notes} onChange={change}/></label><label className="block text-sm font-medium">Giá (VNĐ)<input className="form-input" name="price" type="number" min="0" max="999999999999" step="1" required value={form.price} onChange={change}/></label><label className="block text-sm font-medium">Thời lượng (phút)<input className="form-input" name="duration_minutes" type="number" min="1" max="65535" step="1" required value={form.duration_minutes} onChange={change}/></label><label className="block text-sm font-medium">Trạng thái<select className="form-input" name="status" value={form.status} onChange={change}><option value="active">Hoạt động</option><option value="inactive">Không hoạt động</option></select></label><label className="block text-sm font-medium">Ảnh dịch vụ<input ref={fileInput} className="form-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage}/><span className="mt-1 block text-xs text-stone-500">JPG, PNG, WebP; tối đa 5 MB. Bỏ trống để giữ ảnh cũ.</span></label></div>
  {oldImage&&<img className="h-24 w-36 rounded-lg object-cover" alt="Ảnh hiện tại" src={serviceImageUrl(oldImage)}/>}
  <div className="flex gap-4"><button disabled={busy||!categories.length} className="primary-button">{busy?'Đang xử lý…':'Lưu dịch vụ'}</button>{editId&&<button type="button" disabled={busy} onClick={reset}>Hủy sửa</button>}</div></form>
  {loading?<p role="status">Đang tải…</p>:<div className="overflow-x-auto rounded-xl border border-stone-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-stone-100"><tr><th className="p-4">Dịch vụ</th><th className="p-4">Giá / thời lượng</th><th className="p-4">Trạng thái</th><th className="p-4">Thao tác</th></tr></thead><tbody>{rows.map(row=><tr className="border-t border-stone-100" key={row.id}><td className="p-4"><strong>{row.name}</strong><p className="mt-1 text-stone-500">{row.category_name}</p></td><td className="p-4">{formatPrice(row.price)}<p className="text-stone-500">{row.duration_minutes} phút</p></td><td className="p-4">{row.status==='active'?'Hoạt động':'Không hoạt động'}{row.category_status==='inactive'&&<p className="text-xs text-amber-700">Danh mục đang tắt — ẩn với khách</p>}</td><td className="p-4"><div className="flex gap-4"><button disabled={busy} className="text-emerald-800 underline" onClick={()=>edit(row)}>Sửa</button><button disabled={busy} className="underline" onClick={()=>toggle(row)}>{row.status==='active'?'Tắt':'Bật'}</button></div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-stone-500">Chưa có dịch vụ.</p>}</div>}
  </section>
}
